### ISSUE TITLE
The example in the README is not working

### ISSUE THREAD

**Issue by xyjixyjixyji** [sisshiki1969/monoasm#2]
Hi, this is a very interesting project and i would like to build my own project upon this.

However, seems the example of the README is not working, `jit.finalize()` is not generating the jit compiled function's signature anymore.

Could you please show my any pointer of a simple example using this library to run a jit compile function?

Thanks!

**Comment by sisshiki1969** [comment]
Thank you for your attention! and sorry for skipping out on updating.

I added the sample in `monoasm/tests/vm_fibo.rs`, and README was also fixed.
Please try.

```sh
❯ cargo test --test vm_fibo -- --nocapture
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running tests/vm_fibo.rs (target/debug/deps/vm_fibo-749742d6f31fa80d)

running 1 test
fib( 35 ) = 9227465
test vm_fibo ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
```

**Comment by xyjixyjixyji** [comment]
It works now! And thank you so much for this handy project and updating this!
